# Generated by Django 5.1.3 on 2024-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Покупатель'), ('seller', 'Продавец'), ('admin', 'Администратор')], default='client', max_length=15, verbose_name='роль'),
        ),
    ]
