# Generated by Django 5.1.3 on 2024-11-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cart_options_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='seller',
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/images/'),
        ),
    ]
