# Generated by Django 5.1.3 on 2024-11-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_order_date_alter_cart_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='количество в наличии'),
        ),
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='вес (граммы)'),
        ),
    ]
