# Generated by Django 5.1.3 on 2024-11-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_dish_stock_dish_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='main.category', verbose_name='категории'),
        ),
    ]
