# Generated by Django 5.1.3 on 2024-11-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_dish_category_dish_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='category',
            new_name='categories',
        ),
    ]
